In [16]:
import imageio
import numpy as np
from pathlib import Path
from omegaconf import OmegaConf
import os
from IPython.display import display, Image, HTML
os.environ["OPENCV_IO_ENABLE_OPENEXR"] = "1"
import cv2 as cv
import matplotlib.pyplot as plt
from sklearn import linear_model
import torch.nn.functional as F
import torch
import yaml
import pandas as pd

def disp_im(im):
    plt.close()
    plt.cla()
    fig = plt.imshow(im)
    plt.close()
    display(fig.figure)

In [31]:
exps = ["norussian", "noprednorms_nl0", "noprednorms_nl0_conserve_pb0", 'fixedmip128']
# log_dir = Path("../log") / "norussian"
# log_dir = Path("../log") / "noprednorms_nl0"
rows = []
col_keys = ['psnr', 'ssim', 'l_alex', 'envmap_psnr', 'envmap_smape']
col_rows = {k: [] for k in col_keys}
for exp in exps:
    log_dir = Path("../log") / exp
    col_data = {k: dict(exp=exp) for k in col_keys}
    for p in log_dir.glob("*"):
        pano_path = p / "imgs_test_all" / "envmaps" / "pano.exr"
        mapped_pano_path = p / "imgs_test_all" / "envmaps" / "mapped_pano.png"
        old_data_path = p / "imgs_test_all" / "stats.yaml"
        new_data_path = p / "imgs_test_all" / "stats_aug.yaml"
        config = OmegaConf.load(p / 'config.yaml')
        dname = Path(config['dataset']['scenedir']).name
        if new_data_path.exists():
            with new_data_path.open('r') as f:
                data = yaml.safe_load(f)
        else:
            with old_data_path.open('r') as f:
                data = yaml.safe_load(f)

        if dname == 'shinyball':
            continue
        data['dname'] = dname
        data['exp'] = exp
        rows.append(data)
        for k in col_keys:
            if k in data:
                col_data[k][dname] = data[k]
    for k in col_keys:
        col_data[k]['mean'] = np.mean([v for k, v in col_data[k].items() if type(v) != str])
        col_rows[k].append(col_data[k])

df = pd.DataFrame.from_records(rows)
psnrs = pd.DataFrame.from_dict(col_rows['psnr'])
ssims = pd.DataFrame.from_dict(col_rows['ssim'])
lpips = pd.DataFrame.from_dict(col_rows['l_alex'])
epsnrs = pd.DataFrame.from_dict(col_rows['envmap_psnr'])
display(HTML(psnrs.to_html()))
display(HTML(ssims.to_html()))
display(HTML(lpips.to_html()))
display(HTML(epsnrs.to_html()))

/home/dronelab/miniconda3/envs/31/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dronelab/miniconda3/envs/31/lib/python3.10/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)